/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_rgi_2eproto__INCLUDED
#define PROTOBUF_C_rgi_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Rgi__Setpwmchan Rgi__Setpwmchan;
typedef struct _Rgi__Setpwmchans Rgi__Setpwmchans;
typedef struct _Rgi__Gpiolineon Rgi__Gpiolineon;
typedef struct _Rgi__Gpiolineoff Rgi__Gpiolineoff;


/* --- enums --- */


/* --- messages --- */

struct  _Rgi__Setpwmchan
{
  ProtobufCMessage base;
  uint32_t channel;
  uint32_t value;
};
#define RGI__SETPWMCHAN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rgi__setpwmchan__descriptor) \
    , 0, 0 }


struct  _Rgi__Setpwmchans
{
  ProtobufCMessage base;
  uint32_t value1;
  uint32_t value2;
};
#define RGI__SETPWMCHANS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rgi__setpwmchans__descriptor) \
    , 0, 0 }


struct  _Rgi__Gpiolineon
{
  ProtobufCMessage base;
  uint32_t line;
};
#define RGI__GPIOLINEON__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rgi__gpiolineon__descriptor) \
    , 0 }


struct  _Rgi__Gpiolineoff
{
  ProtobufCMessage base;
  uint32_t line;
};
#define RGI__GPIOLINEOFF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rgi__gpiolineoff__descriptor) \
    , 0 }


/* Rgi__Setpwmchan methods */
void   rgi__setpwmchan__init
                     (Rgi__Setpwmchan         *message);
size_t rgi__setpwmchan__get_packed_size
                     (const Rgi__Setpwmchan   *message);
size_t rgi__setpwmchan__pack
                     (const Rgi__Setpwmchan   *message,
                      uint8_t             *out);
size_t rgi__setpwmchan__pack_to_buffer
                     (const Rgi__Setpwmchan   *message,
                      ProtobufCBuffer     *buffer);
Rgi__Setpwmchan *
       rgi__setpwmchan__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rgi__setpwmchan__free_unpacked
                     (Rgi__Setpwmchan *message,
                      ProtobufCAllocator *allocator);
/* Rgi__Setpwmchans methods */
void   rgi__setpwmchans__init
                     (Rgi__Setpwmchans         *message);
size_t rgi__setpwmchans__get_packed_size
                     (const Rgi__Setpwmchans   *message);
size_t rgi__setpwmchans__pack
                     (const Rgi__Setpwmchans   *message,
                      uint8_t             *out);
size_t rgi__setpwmchans__pack_to_buffer
                     (const Rgi__Setpwmchans   *message,
                      ProtobufCBuffer     *buffer);
Rgi__Setpwmchans *
       rgi__setpwmchans__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rgi__setpwmchans__free_unpacked
                     (Rgi__Setpwmchans *message,
                      ProtobufCAllocator *allocator);
/* Rgi__Gpiolineon methods */
void   rgi__gpiolineon__init
                     (Rgi__Gpiolineon         *message);
size_t rgi__gpiolineon__get_packed_size
                     (const Rgi__Gpiolineon   *message);
size_t rgi__gpiolineon__pack
                     (const Rgi__Gpiolineon   *message,
                      uint8_t             *out);
size_t rgi__gpiolineon__pack_to_buffer
                     (const Rgi__Gpiolineon   *message,
                      ProtobufCBuffer     *buffer);
Rgi__Gpiolineon *
       rgi__gpiolineon__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rgi__gpiolineon__free_unpacked
                     (Rgi__Gpiolineon *message,
                      ProtobufCAllocator *allocator);
/* Rgi__Gpiolineoff methods */
void   rgi__gpiolineoff__init
                     (Rgi__Gpiolineoff         *message);
size_t rgi__gpiolineoff__get_packed_size
                     (const Rgi__Gpiolineoff   *message);
size_t rgi__gpiolineoff__pack
                     (const Rgi__Gpiolineoff   *message,
                      uint8_t             *out);
size_t rgi__gpiolineoff__pack_to_buffer
                     (const Rgi__Gpiolineoff   *message,
                      ProtobufCBuffer     *buffer);
Rgi__Gpiolineoff *
       rgi__gpiolineoff__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rgi__gpiolineoff__free_unpacked
                     (Rgi__Gpiolineoff *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Rgi__Setpwmchan_Closure)
                 (const Rgi__Setpwmchan *message,
                  void *closure_data);
typedef void (*Rgi__Setpwmchans_Closure)
                 (const Rgi__Setpwmchans *message,
                  void *closure_data);
typedef void (*Rgi__Gpiolineon_Closure)
                 (const Rgi__Gpiolineon *message,
                  void *closure_data);
typedef void (*Rgi__Gpiolineoff_Closure)
                 (const Rgi__Gpiolineoff *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor rgi__setpwmchan__descriptor;
extern const ProtobufCMessageDescriptor rgi__setpwmchans__descriptor;
extern const ProtobufCMessageDescriptor rgi__gpiolineon__descriptor;
extern const ProtobufCMessageDescriptor rgi__gpiolineoff__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_rgi_2eproto__INCLUDED */
