/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "rgi.pb-c.h"
void   rgi__setpwmchan__init
                     (Rgi__Setpwmchan         *message)
{
  static Rgi__Setpwmchan init_value = RGI__SETPWMCHAN__INIT;
  *message = init_value;
}
size_t rgi__setpwmchan__get_packed_size
                     (const Rgi__Setpwmchan *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setpwmchan__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rgi__setpwmchan__pack
                     (const Rgi__Setpwmchan *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setpwmchan__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rgi__setpwmchan__pack_to_buffer
                     (const Rgi__Setpwmchan *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setpwmchan__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rgi__Setpwmchan *
       rgi__setpwmchan__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rgi__Setpwmchan *)
     protobuf_c_message_unpack (&rgi__setpwmchan__descriptor,
                                allocator, len, data);
}
void   rgi__setpwmchan__free_unpacked
                     (Rgi__Setpwmchan *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setpwmchan__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rgi__setpwmchans__init
                     (Rgi__Setpwmchans         *message)
{
  static Rgi__Setpwmchans init_value = RGI__SETPWMCHANS__INIT;
  *message = init_value;
}
size_t rgi__setpwmchans__get_packed_size
                     (const Rgi__Setpwmchans *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setpwmchans__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rgi__setpwmchans__pack
                     (const Rgi__Setpwmchans *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setpwmchans__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rgi__setpwmchans__pack_to_buffer
                     (const Rgi__Setpwmchans *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setpwmchans__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rgi__Setpwmchans *
       rgi__setpwmchans__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rgi__Setpwmchans *)
     protobuf_c_message_unpack (&rgi__setpwmchans__descriptor,
                                allocator, len, data);
}
void   rgi__setpwmchans__free_unpacked
                     (Rgi__Setpwmchans *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setpwmchans__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rgi__gpiolineon__init
                     (Rgi__Gpiolineon         *message)
{
  static Rgi__Gpiolineon init_value = RGI__GPIOLINEON__INIT;
  *message = init_value;
}
size_t rgi__gpiolineon__get_packed_size
                     (const Rgi__Gpiolineon *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__gpiolineon__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rgi__gpiolineon__pack
                     (const Rgi__Gpiolineon *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__gpiolineon__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rgi__gpiolineon__pack_to_buffer
                     (const Rgi__Gpiolineon *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__gpiolineon__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rgi__Gpiolineon *
       rgi__gpiolineon__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rgi__Gpiolineon *)
     protobuf_c_message_unpack (&rgi__gpiolineon__descriptor,
                                allocator, len, data);
}
void   rgi__gpiolineon__free_unpacked
                     (Rgi__Gpiolineon *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__gpiolineon__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rgi__gpiolineoff__init
                     (Rgi__Gpiolineoff         *message)
{
  static Rgi__Gpiolineoff init_value = RGI__GPIOLINEOFF__INIT;
  *message = init_value;
}
size_t rgi__gpiolineoff__get_packed_size
                     (const Rgi__Gpiolineoff *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__gpiolineoff__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rgi__gpiolineoff__pack
                     (const Rgi__Gpiolineoff *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__gpiolineoff__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rgi__gpiolineoff__pack_to_buffer
                     (const Rgi__Gpiolineoff *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__gpiolineoff__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rgi__Gpiolineoff *
       rgi__gpiolineoff__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rgi__Gpiolineoff *)
     protobuf_c_message_unpack (&rgi__gpiolineoff__descriptor,
                                allocator, len, data);
}
void   rgi__gpiolineoff__free_unpacked
                     (Rgi__Gpiolineoff *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__gpiolineoff__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rgi__tellid__init
                     (Rgi__Tellid         *message)
{
  static Rgi__Tellid init_value = RGI__TELLID__INIT;
  *message = init_value;
}
size_t rgi__tellid__get_packed_size
                     (const Rgi__Tellid *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__tellid__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rgi__tellid__pack
                     (const Rgi__Tellid *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__tellid__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rgi__tellid__pack_to_buffer
                     (const Rgi__Tellid *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__tellid__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rgi__Tellid *
       rgi__tellid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rgi__Tellid *)
     protobuf_c_message_unpack (&rgi__tellid__descriptor,
                                allocator, len, data);
}
void   rgi__tellid__free_unpacked
                     (Rgi__Tellid *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__tellid__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rgi__setlock__init
                     (Rgi__Setlock         *message)
{
  static Rgi__Setlock init_value = RGI__SETLOCK__INIT;
  *message = init_value;
}
size_t rgi__setlock__get_packed_size
                     (const Rgi__Setlock *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setlock__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rgi__setlock__pack
                     (const Rgi__Setlock *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setlock__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rgi__setlock__pack_to_buffer
                     (const Rgi__Setlock *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setlock__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rgi__Setlock *
       rgi__setlock__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rgi__Setlock *)
     protobuf_c_message_unpack (&rgi__setlock__descriptor,
                                allocator, len, data);
}
void   rgi__setlock__free_unpacked
                     (Rgi__Setlock *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setlock__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rgi__setunlock__init
                     (Rgi__Setunlock         *message)
{
  static Rgi__Setunlock init_value = RGI__SETUNLOCK__INIT;
  *message = init_value;
}
size_t rgi__setunlock__get_packed_size
                     (const Rgi__Setunlock *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setunlock__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rgi__setunlock__pack
                     (const Rgi__Setunlock *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setunlock__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rgi__setunlock__pack_to_buffer
                     (const Rgi__Setunlock *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setunlock__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rgi__Setunlock *
       rgi__setunlock__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rgi__Setunlock *)
     protobuf_c_message_unpack (&rgi__setunlock__descriptor,
                                allocator, len, data);
}
void   rgi__setunlock__free_unpacked
                     (Rgi__Setunlock *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__setunlock__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rgi__telllocked__init
                     (Rgi__Telllocked         *message)
{
  static Rgi__Telllocked init_value = RGI__TELLLOCKED__INIT;
  *message = init_value;
}
size_t rgi__telllocked__get_packed_size
                     (const Rgi__Telllocked *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__telllocked__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rgi__telllocked__pack
                     (const Rgi__Telllocked *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__telllocked__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rgi__telllocked__pack_to_buffer
                     (const Rgi__Telllocked *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__telllocked__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rgi__Telllocked *
       rgi__telllocked__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rgi__Telllocked *)
     protobuf_c_message_unpack (&rgi__telllocked__descriptor,
                                allocator, len, data);
}
void   rgi__telllocked__free_unpacked
                     (Rgi__Telllocked *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__telllocked__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rgi__tellready__init
                     (Rgi__Tellready         *message)
{
  static Rgi__Tellready init_value = RGI__TELLREADY__INIT;
  *message = init_value;
}
size_t rgi__tellready__get_packed_size
                     (const Rgi__Tellready *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__tellready__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rgi__tellready__pack
                     (const Rgi__Tellready *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__tellready__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rgi__tellready__pack_to_buffer
                     (const Rgi__Tellready *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__tellready__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rgi__Tellready *
       rgi__tellready__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rgi__Tellready *)
     protobuf_c_message_unpack (&rgi__tellready__descriptor,
                                allocator, len, data);
}
void   rgi__tellready__free_unpacked
                     (Rgi__Tellready *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__tellready__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rgi__getadcchannel__init
                     (Rgi__Getadcchannel         *message)
{
  static Rgi__Getadcchannel init_value = RGI__GETADCCHANNEL__INIT;
  *message = init_value;
}
size_t rgi__getadcchannel__get_packed_size
                     (const Rgi__Getadcchannel *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__getadcchannel__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rgi__getadcchannel__pack
                     (const Rgi__Getadcchannel *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__getadcchannel__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rgi__getadcchannel__pack_to_buffer
                     (const Rgi__Getadcchannel *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__getadcchannel__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rgi__Getadcchannel *
       rgi__getadcchannel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rgi__Getadcchannel *)
     protobuf_c_message_unpack (&rgi__getadcchannel__descriptor,
                                allocator, len, data);
}
void   rgi__getadcchannel__free_unpacked
                     (Rgi__Getadcchannel *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__getadcchannel__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rgi__telladcchannel__init
                     (Rgi__Telladcchannel         *message)
{
  static Rgi__Telladcchannel init_value = RGI__TELLADCCHANNEL__INIT;
  *message = init_value;
}
size_t rgi__telladcchannel__get_packed_size
                     (const Rgi__Telladcchannel *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__telladcchannel__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rgi__telladcchannel__pack
                     (const Rgi__Telladcchannel *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__telladcchannel__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rgi__telladcchannel__pack_to_buffer
                     (const Rgi__Telladcchannel *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__telladcchannel__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rgi__Telladcchannel *
       rgi__telladcchannel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rgi__Telladcchannel *)
     protobuf_c_message_unpack (&rgi__telladcchannel__descriptor,
                                allocator, len, data);
}
void   rgi__telladcchannel__free_unpacked
                     (Rgi__Telladcchannel *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &rgi__telladcchannel__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rgi__setpwmchan__field_descriptors[2] =
{
  {
    "channel",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Setpwmchan, channel),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Setpwmchan, value),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned rgi__setpwmchan__field_indices_by_name[] = {
  0,   /* field[0] = channel */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange rgi__setpwmchan__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rgi__setpwmchan__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rgi.setpwmchan",
  "Setpwmchan",
  "Rgi__Setpwmchan",
  "rgi",
  sizeof(Rgi__Setpwmchan),
  2,
  rgi__setpwmchan__field_descriptors,
  rgi__setpwmchan__field_indices_by_name,
  1,  rgi__setpwmchan__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rgi__setpwmchans__field_descriptors[2] =
{
  {
    "value1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Setpwmchans, value1),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "value2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Setpwmchans, value2),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned rgi__setpwmchans__field_indices_by_name[] = {
  0,   /* field[0] = value1 */
  1,   /* field[1] = value2 */
};
static const ProtobufCIntRange rgi__setpwmchans__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rgi__setpwmchans__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rgi.setpwmchans",
  "Setpwmchans",
  "Rgi__Setpwmchans",
  "rgi",
  sizeof(Rgi__Setpwmchans),
  2,
  rgi__setpwmchans__field_descriptors,
  rgi__setpwmchans__field_indices_by_name,
  1,  rgi__setpwmchans__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rgi__gpiolineon__field_descriptors[1] =
{
  {
    "line",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Gpiolineon, line),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned rgi__gpiolineon__field_indices_by_name[] = {
  0,   /* field[0] = line */
};
static const ProtobufCIntRange rgi__gpiolineon__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rgi__gpiolineon__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rgi.gpiolineon",
  "Gpiolineon",
  "Rgi__Gpiolineon",
  "rgi",
  sizeof(Rgi__Gpiolineon),
  1,
  rgi__gpiolineon__field_descriptors,
  rgi__gpiolineon__field_indices_by_name,
  1,  rgi__gpiolineon__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rgi__gpiolineoff__field_descriptors[1] =
{
  {
    "line",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Gpiolineoff, line),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned rgi__gpiolineoff__field_indices_by_name[] = {
  0,   /* field[0] = line */
};
static const ProtobufCIntRange rgi__gpiolineoff__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rgi__gpiolineoff__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rgi.gpiolineoff",
  "Gpiolineoff",
  "Rgi__Gpiolineoff",
  "rgi",
  sizeof(Rgi__Gpiolineoff),
  1,
  rgi__gpiolineoff__field_descriptors,
  rgi__gpiolineoff__field_indices_by_name,
  1,  rgi__gpiolineoff__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rgi__tellid__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Tellid, id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned rgi__tellid__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange rgi__tellid__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rgi__tellid__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rgi.tellid",
  "Tellid",
  "Rgi__Tellid",
  "rgi",
  sizeof(Rgi__Tellid),
  1,
  rgi__tellid__field_descriptors,
  rgi__tellid__field_indices_by_name,
  1,  rgi__tellid__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rgi__setlock__field_descriptors[1] =
{
  {
    "lock",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Setlock, lock),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned rgi__setlock__field_indices_by_name[] = {
  0,   /* field[0] = lock */
};
static const ProtobufCIntRange rgi__setlock__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rgi__setlock__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rgi.setlock",
  "Setlock",
  "Rgi__Setlock",
  "rgi",
  sizeof(Rgi__Setlock),
  1,
  rgi__setlock__field_descriptors,
  rgi__setlock__field_indices_by_name,
  1,  rgi__setlock__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rgi__setunlock__field_descriptors[1] =
{
  {
    "lock",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Setunlock, lock),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned rgi__setunlock__field_indices_by_name[] = {
  0,   /* field[0] = lock */
};
static const ProtobufCIntRange rgi__setunlock__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rgi__setunlock__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rgi.setunlock",
  "Setunlock",
  "Rgi__Setunlock",
  "rgi",
  sizeof(Rgi__Setunlock),
  1,
  rgi__setunlock__field_descriptors,
  rgi__setunlock__field_indices_by_name,
  1,  rgi__setunlock__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rgi__telllocked__field_descriptors[1] =
{
  {
    "lock",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Telllocked, lock),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned rgi__telllocked__field_indices_by_name[] = {
  0,   /* field[0] = lock */
};
static const ProtobufCIntRange rgi__telllocked__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rgi__telllocked__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rgi.telllocked",
  "Telllocked",
  "Rgi__Telllocked",
  "rgi",
  sizeof(Rgi__Telllocked),
  1,
  rgi__telllocked__field_descriptors,
  rgi__telllocked__field_indices_by_name,
  1,  rgi__telllocked__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rgi__tellready__field_descriptors[1] =
{
  {
    "lock",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Tellready, lock),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned rgi__tellready__field_indices_by_name[] = {
  0,   /* field[0] = lock */
};
static const ProtobufCIntRange rgi__tellready__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rgi__tellready__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rgi.tellready",
  "Tellready",
  "Rgi__Tellready",
  "rgi",
  sizeof(Rgi__Tellready),
  1,
  rgi__tellready__field_descriptors,
  rgi__tellready__field_indices_by_name,
  1,  rgi__tellready__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rgi__getadcchannel__field_descriptors[1] =
{
  {
    "channel",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Getadcchannel, channel),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned rgi__getadcchannel__field_indices_by_name[] = {
  0,   /* field[0] = channel */
};
static const ProtobufCIntRange rgi__getadcchannel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rgi__getadcchannel__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rgi.getadcchannel",
  "Getadcchannel",
  "Rgi__Getadcchannel",
  "rgi",
  sizeof(Rgi__Getadcchannel),
  1,
  rgi__getadcchannel__field_descriptors,
  rgi__getadcchannel__field_indices_by_name,
  1,  rgi__getadcchannel__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rgi__telladcchannel__field_descriptors[2] =
{
  {
    "channel",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Telladcchannel, channel),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Rgi__Telladcchannel, value),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned rgi__telladcchannel__field_indices_by_name[] = {
  0,   /* field[0] = channel */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange rgi__telladcchannel__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rgi__telladcchannel__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "rgi.telladcchannel",
  "Telladcchannel",
  "Rgi__Telladcchannel",
  "rgi",
  sizeof(Rgi__Telladcchannel),
  2,
  rgi__telladcchannel__field_descriptors,
  rgi__telladcchannel__field_indices_by_name,
  1,  rgi__telladcchannel__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
